[pyprland]
plugins = [
  "scratchpads",
  "expose",
  "shortcuts_menu",
  "toggle_special",
]

[scratchpads.term]
command = "wezterm start --always-new-process --class wezterm_dropdown"
animation = "fromTop"
unfocus = "hide"
excludes = "*"
lazy = true
multi = false

# [shortcuts_menu.entries]
